const Map<String, String> stringsHi = {
  // App General
  'app_name': 'CarePlus',
  'tagline': 'सेहत की सरल और सुरक्षित मार्गदर्शिका',
  'disclaimer_title': 'चिकित्सा सुरक्षा और अस्वीकरण',
  'disclaimer_text':
      'CarePlus केवल सामान्य स्वास्थ्य जानकारी और शैक्षिक मार्गदर्शन प्रदान करता है। यह किसी डॉक्टर, औपचारिक निदान या आपातकालीन चिकित्सा सेवा का विकल्प नहीं है। किसी भी दवा को शुरू, बंद या बदलने से पहले हमेशा योग्य डॉक्टर से परामर्श लें। आपात स्थिति में तुरंत नजदीकी आपातकालीन सेवा से संपर्क करें।',
  'disclaimer_accept': 'मैं समझता हूँ और सहमत हूँ',
  'disclaimer_decline': 'अस्वीकार करें',

  // Navigation
  'nav_home': 'होम',
  'nav_my_health': 'मेरा स्वास्थ्य',
  'nav_suggestions': 'सुझाव',
  'nav_profile': 'प्रोफ़ाइल',
  'nav_ai_assistant': 'CarePlus AI',

  // Home Screen
  'home_greeting': 'नमस्ते, CarePlus में आपका स्वागत है',
  'home_subtext': 'अपनी स्वास्थ्य समस्या दर्ज करें और व्यक्तिगत सामान्य मार्गदर्शन प्राप्त करें।',
  'home_main_cta': 'स्वास्थ्य जांचें (Check My Health)',
  'home_quick_options': 'त्वरित स्वास्थ्य उपकरण',
  'quick_problem': 'स्वास्थ्य समस्या',
  'quick_food': 'आहार और पोषण',
  'quick_yoga': 'योग और व्यायाम',
  'quick_medicine': 'दवा सुरक्षा',
  'quick_doctor': 'डॉक्टर परामर्श',
  'quick_emergency': 'आपातकालीन सहायता',
  'recent_checks': 'हाल की स्वास्थ्य जांच',
  'no_recent_checks': 'कोई पुरानी जांच नहीं है। "स्वास्थ्य जांचें" पर टैप करें।',
  'view_all_history': 'पूरा इतिहास देखें',
  'daily_tip_title': 'दैनिक स्वास्थ्य सुझाव',
  'daily_tip_body': 'रोजाना 8-10 गिलास पानी पीने से पाचन अच्छा रहता है और शरीर ऊर्जावान रहता है।',

  // Patient Info Form
  'patient_info_title': 'रोगी की सामान्य जानकारी',
  'patient_info_subtitle': 'उचित मार्गदर्शन के लिए कृपया बुनियादी विवरण भरें।',
  'full_name': 'पूरा नाम',
  'full_name_hint': 'उदा. राजेश शर्मा',
  'age': 'आयु (वर्ष)',
  'age_hint': 'उदा. 35',
  'gender': 'लिंग',
  'gender_male': 'पुरुष',
  'gender_female': 'महिला',
  'gender_other': 'अन्य',
  'weight_kg': 'वजन (किग्रा)',
  'height_cm': 'कद (सेमी)',
  'location': 'स्थान / शहर (वैकल्पिक)',
  'location_hint': 'उदा. नई दिल्ली, लखनऊ',
  'pregnancy_question': 'क्या रोगी गर्भवती हैं?',
  'yes': 'हाँ',
  'no': 'नहीं',
  'btn_next': 'आगे बढ़ें: समस्या विवरण',
  'btn_get_suggestions': 'सुझाव प्राप्त करें',

  // Problem & Symptom Input
  'problem_input_title': 'स्वास्थ्य समस्या और लक्षण',
  'problem_input_subtitle': 'अपनी समस्या को सरल शब्दों में लिखें।',
  'problem_hint': 'उदा. सुबह से सिर में दर्द है, पेट में जलन हो रही है...',
  'select_common_problems': 'या सामान्य समस्याएं चुनें:',
  'symptoms_title': 'संबंधित लक्षण चुनें',
  'symptoms_search_hint': 'लक्षण खोजें (उदा. बुखार, उल्टी, दर्द)',
  'duration_title': 'यह समस्या कब से है?',
  'duration_1day': 'आज से / 24 घंटे से कम',
  'duration_few_days': '2 – 3 दिन से',
  'duration_1week': '1 – 2 सप्ताह से',
  'duration_chronic': 'एक महीने से अधिक',
  'existing_conditions': 'पूर्व में कोई बीमारी? (वैकल्पिक)',
  'existing_conditions_hint': 'उदा. मधुमेह, उच्च रक्तचाप, थायराइड, अस्थमा',
  'current_medicines': 'वर्तमान में चल रही दवाएं',
  'current_medicines_hint': 'उदा. मेटफॉर्मिन, बीपी की गोली',
  'allergies': 'एलर्जी (यदि कोई हो)',
  'allergies_hint': 'उदा. धूल, पेनिसिलिन, मूंगफली',
  'btn_analyze': 'विश्लेषण करें और मार्गदर्शन पाएं',

  // Health Analysis
  'analysis_in_progress': 'स्वास्थ्य विश्लेषण चल रहा है...',
  'analysis_subtext': 'लक्षणों, आहार और व्यायाम सुझावों का मूल्यांकन किया जा रहा है...',

  // Health Result / Guidance Screen
  'result_title': 'आपका स्वास्थ्य मार्गदर्शन',
  'tab_overview': 'विवरण',
  'tab_food': 'आहार',
  'tab_yoga': 'योग/व्यायाम',
  'tab_medicine': 'दवा सुरक्षा',
  'tab_doctor': 'डॉक्टर सलाह',
  'reported_problem': 'दर्ज समस्या',
  'risk_level': 'मार्गदर्शन स्तर',
  'risk_low': 'सामान्य / घरेलू देखभाल',
  'risk_moderate': 'मध्यम — सावधानी से देखभाल करें',
  'risk_consult': 'डॉक्टर से परामर्श की सिफारिश की जाती है',
  'risk_emergency': 'आपातकाल: तुरंत चिकित्सा सहायता लें',
  'possible_causes_title': 'संभावित कारण',
  'possible_causes_disclaimer': 'नोट: यह सामान्य जानकारी है, कोई पुष्ट निदान नहीं है। सटीक जांच के लिए चिकित्सक से मिलें।',
  'general_tips': 'सामान्य स्वास्थ्य सुझाव',

  // Food Section
  'food_title': 'आहार और पोषण सुझाव',
  'food_recommended': 'खाने योग्य अनुशंसित खाद्य पदार्थ',
  'food_to_avoid': 'परहेज योग्य खाद्य पदार्थ',
  'hydration_guidance': 'तरल पदार्थ और पानी की सलाह',
  'food_safety_note': 'यह आहार सुझाव आपकी दी गई एलर्जी जानकारी के आधार पर तैयार किया गया है।',

  // Yoga Section
  'yoga_title': 'योग और सौम्य व्यायाम',
  'yoga_safety_warning': '⚠️ यदि आपको कोई गंभीर दर्द या पुरानी बीमारी है, तो व्यायाम शुरू करने से पहले डॉक्टर से परामर्श लें।',
  'duration_label': 'अवधि',
  'instructions_label': 'निर्देश',
  'precautions_label': 'सावधानियां',

  // Medicine Safety
  'medicine_safety_title': 'दवा सुरक्षा और सामान्य ज्ञान',
  'medicine_mandatory_warning': '⚠️ महत्वपूर्ण: किसी भी दवा को लेने, बंद करने या खुराक बदलने से पहले योग्य डॉक्टर या फार्मासिस्ट से परामर्श अवश्य लें।',
  'medicine_purpose': 'सामान्य उद्देश्य',
  'medicine_precautions': 'आवश्यक सावधानियां',
  'medicine_side_effects': 'सामान्य दुष्प्रभाव (Side Effects)',
  'medicine_who_should_ask': 'किन्हें पहले डॉक्टर से पूछना चाहिए?',
  'medicine_source': 'सत्यापित स्रोत',

  // Doctor Consultation
  'doctor_title': 'डॉक्टर परामर्श',
  'doctor_recommended_msg': 'शारीरिक जांच और सटीक निदान के लिए योग्य चिकित्सक से मिलना उचित है।',
  'btn_find_doctor': 'डॉक्टर खोजें',
  'btn_book_consult': 'ऑनलाइन परामर्श बुक करें',
  'btn_call_helpline': 'हेल्पलाइन पर कॉल करें',
  'btn_save_report': 'स्वास्थ्य रिपोर्ट सहेजें',

  // Emergency Alert
  'emergency_alert_title': '🚨 आपातकालीन चेतावनी',
  'emergency_alert_msg': 'यह लक्षण गंभीर स्थिति का संकेत हो सकते हैं। कृपया तुरंत आपातकालीन चिकित्सा सहायता लें।',
  'emergency_call_btn': 'आपातकालीन कॉल (112 / 108)',
  'emergency_nearby_hospital': 'निकटतम अस्पताल खोजें',

  // My Health Profile
  'profile_title': 'मेरा स्वास्थ्य प्रोफ़ाइल',
  'profile_bmi': 'बॉडी मास इंडेक्स (BMI)',
  'bmi_underweight': 'कम वजन (<18.5)',
  'bmi_normal': 'सामान्य और स्वस्थ (18.5 - 24.9)',
  'bmi_overweight': 'अधिक वजन (25 - 29.9)',
  'bmi_obese': 'मोटापा (≥30)',
  'edit_profile': 'प्रोफ़ाइल संपादित करें',
  'saved_conditions': 'पुरानी बीमारियां',
  'saved_allergies': 'ज्ञात एलर्जी',
  'saved_medicines': 'सक्रिय दवाएं',
  'health_records_count': 'कुल स्वास्थ्य जांचें',

  // AI Assistant
  'ai_assistant_title': 'CarePlus AI सहायक',
  'ai_welcome_msg': 'नमस्ते! मैं CarePlus AI हूँ। मुझसे सामान्य स्वास्थ्य, आहार, योग या दवा सुरक्षा संबंधी प्रश्न पूछ सकते हैं।',
  'ai_quick_prompt_1': 'एसिडिटी होने पर क्या खाना चाहिए?',
  'ai_quick_prompt_2': 'कमर दर्द के लिए सुरक्षित व्यायाम बताएं',
  'ai_quick_prompt_3': 'सिरदर्द के घरेलू उपाय',
  'ai_quick_prompt_4': 'पैरासिटामोल के लिए सामान्य सावधानियां',
  'ai_type_hint': 'अपना प्रश्न हिन्दी में पूछें...',
  'ai_disclaimer_tag': 'CarePlus AI केवल शैक्षिक जानकारी देता है, दवा का नुस्खा नहीं।',

  // Admin & Settings
  'settings_title': 'सेटिंग्स और गोपनीयता',
  'theme_mode': 'थीम मोड (लाइट / डार्क)',
  'theme_switch_dark': 'डार्क मोड चालू करें',
  'theme_switch_light': 'लाइट मोड चालू करें',
  'language_mode': 'ऐप की भाषा',
  'elderly_mode': 'बड़े अक्षर मोड (बुजुर्गों के लिए)',
  'elderly_mode_desc': 'आसानी से पढ़ने के लिए फॉन्ट का आकार बड़ा करता है।',
  'admin_panel': 'एडमिन डैशबोर्ड',
  'privacy_policy': 'गोपनीयता नीति और डेटा सुरक्षा',
  'terms_of_service': 'नियम और शर्तें',
  'clear_health_data': 'स्वास्थ्य डेटा हटाएं',
  'delete_account': 'खाता हटाएं',
  'logout': 'लॉग आउट',
  'confirm_clear_data': 'क्या आप वाकई अपना सहेजा गया स्वास्थ्य डेटा हटाना चाहते हैं?',
  'cancel': 'रद्द करें',
  'confirm': 'हटाएं',
  'data_cleared_success': 'डेटा सफलतापूर्वक हटा दिया गया।',
  'error_generic': 'कुछ त्रुटि हुई। कृपया पुनः प्रयास करें।',
};
