const Map<String, String> stringsHinglish = {
  // App General
  'app_name': 'CarePlus',
  'tagline': 'Sehat ki simple aur safe guidance.',
  'disclaimer_title': 'Medical Safety & Guidance Disclaimer',
  'disclaimer_text':
      'CarePlus general health information aur guidance provide karta hai. Ye doctor, diagnosis ya emergency medical service ka replacement nahi hai. Kisi bhi medicine ko start, stop ya change karne se pehle qualified healthcare professional se salah lein. Emergency situation me turant local emergency medical services se contact karein.',
  'disclaimer_accept': 'Main samajh gaya / Accept',
  'disclaimer_decline': 'Decline',

  // Navigation
  'nav_home': 'Home',
  'nav_my_health': 'My Health',
  'nav_suggestions': 'Suggestions',
  'nav_profile': 'Profile',
  'nav_ai_assistant': 'CarePlus AI',

  // Home Screen & Tabs
  'tab_diabetes': 'Diabetes',
  'tab_other': 'Other',
  'home_greeting': 'Hello, Welcome to CarePlus',
  'home_subtext': 'Apni health problem enter karein aur personalized general guidance paayein.',
  'home_main_cta': 'Check My Health',
  'diabetes_greeting': 'Diabetes aur Sugar Care',
  'diabetes_subtext': 'High/Low sugar, diet, walking aur blood sugar control ki safe guidance.',
  'diabetes_main_cta': 'Diabetes Checkup Shuru Karein',
  'home_quick_options': 'Quick Health Tools',
  'diabetes_quick_problems': 'Diabetes & Sugar Concerns',
  'quick_problem': 'Health Problem',
  'quick_food': 'Food & Diet',
  'quick_yoga': 'Yoga & Exercise',
  'quick_medicine': 'Medicine Safety',
  'quick_doctor': 'Doctor Consultation',
  'quick_emergency': 'Emergency Help',
  'recent_checks': 'Recent Health Checks',
  'no_recent_checks': 'Koi previous check nahi hai. "Start Health Checkup" dabayein.',
  'view_all_history': 'Pura History Dekhein',
  'daily_tip_title': 'Sehat Ki Baat (Daily Tip)',
  'daily_tip_body': 'Rozana 8-10 glass paani peene se digestion acha rehta hai aur body active rehti hai.',
  'diabetes_daily_tip_title': 'Daily Sugar Control Tip',
  'diabetes_daily_tip_body': 'Khana khane ke baad 15 minute ki walk karne se blood sugar spike nahi hota aur insulin behtar kaam karta hai.',
  'diabetes_home_remedies_title': 'Sugar Control Ke Liye Gharelu Tips',
  'diabetes_specialists_title': 'Top Verified Diabetologists',
  'other_specialists_title': 'Top Verified Specialists',
  'book_appointment': 'Book Consult',
  'call_clinic': 'Call Clinic',

  // Home Screen Banners & Remedies
  'safe_guidance_engine': 'Safe Guidance Engine',
  'blood_sugar_engine': 'Blood Sugar Safety Engine',
  'start_health_checkup': 'Start Health Checkup',
  'general_checkup_sub': 'Symptoms enter karein aur food, yoga aur medicine guidance paayein.',
  'diabetes_checkup_sub': 'Blood sugar control, low sugar, diet aur safety guidance check karein.',
  'methi_title': 'Gunguna Paani & Methi Dana',
  'methi_desc': 'Subah 1 tsp bheega methi dana fasting sugar control me madad karta hai.',
  'low_gi_title': 'Low GI Diet',
  'low_gi_desc': 'Moong dal, oats aur leafy veggies lein; maida aur meetha avoid karein.',
  'walk_title': 'Khane Ke Baad 15 Min Walk',
  'walk_desc': 'Khane ke baad 15 min brisk walk glucose spike kam karti hai.',
  'foot_title': 'Rozana Feet Check Karein',
  'foot_desc': 'Diabetes me feet clean rakhein aur cuts ke liye check karein.',

  // Patient Info Form
  'patient_info_title': 'Patient Ki Basic Jankari',
  'patient_info_subtitle': 'Sahi suggestions ke liye kripya basic details fill karein.',
  'step_1_of_2': 'Step 1 of 2',
  'step_2_of_2': 'Step 2 of 2',
  'personal_details': 'Personal Details',
  'problem_symptoms_title': 'Problem & Symptoms',
  'full_name': 'Pura Naam',
  'full_name_hint': 'jaise Anita Sharma / Rajesh Kumar',
  'age': 'Umar (Age in years)',
  'age_hint': 'jaise 35',
  'gender': 'Gender (Ling)',
  'gender_male': 'Purush (Male)',
  'gender_female': 'Mahila (Female)',
  'gender_other': 'Other',
  'weight_kg': 'Wajan (Weight in kg)',
  'height_cm': 'Height (cm me)',
  'location': 'City / Location (Optional)',
  'location_hint': 'jaise Mumbai, Delhi, Lucknow',
  'pregnancy_question': 'Kya patient pregnant hain?',
  'yes': 'Haan (Yes)',
  'no': 'Nahi (No)',
  'btn_next': 'Aage Badhein: Problem Details',
  'btn_get_suggestions': 'Suggestions Paayein',

  // Problem & Symptom Input
  'problem_input_title': 'Apni Health Problem Batayein',
  'problem_input_subtitle': 'Aapko kya takleef hai, simple shabdon me likhein.',
  'problem_hint': 'jaise: Pet me dard hai, sir bhari rehta hai, acidity hai...',
  'select_common_problems': 'Ya niche se common problem chunein:',
  'symptoms_title': 'Symptoms (Lakshan) Select Karein',
  'symptoms_search_hint': 'Lakshan search karein (jaise Fever, Vomiting, Pain)',
  'duration_title': 'Problem kab se hai?',
  'duration_1day': 'Aaj se / 24 ghante se kam',
  'duration_few_days': '2 – 3 din se',
  'duration_1week': '1 – 2 hafte se',
  'duration_chronic': 'Ek mahine se zyada',
  'existing_conditions': 'Pehle se koi bimari hai? (Optional)',
  'existing_conditions_hint': 'jaise Diabetes, High BP, Thyroid, Asthma',
  'current_medicines': 'Abhi kaunsi medicine chal rahi hai?',
  'current_medicines_hint': 'jaise Metformin, BP tablet, Gas capsule',
  'allergies': 'Kisi cheez se allergy hai? (Optional)',
  'allergies_hint': 'jaise Dust, Penicillin, Peanuts',
  'btn_analyze': 'Analyze Karein & Guidance Paayein',

  // Health Analysis
  'analysis_in_progress': 'Health Analysis Chal Raha Hai...',
  'analysis_subtext': 'Symptoms, risk level, food aur exercise suggestions ready kiye ja rahe hain...',

  // Health Result / Guidance Screen
  'result_title': 'Aapki Health Guidance',
  'tab_overview': 'Overview',
  'tab_food': 'Food & Diet',
  'tab_yoga': 'Yoga & Exercise',
  'tab_medicine': 'Medicine Safety',
  'tab_doctor': 'Doctor Advice',
  'tab_medicine_short': 'Medicine',
  'tab_food_short': 'Food & Diet',
  'tab_yoga_short': 'Yoga & Ex.',
  'tab_doctor_short': 'Doctor',
  'medicine_summary_title': 'Medicine Summary',
  'summary_medicine_name': 'Medicine Name',
  'diet_summary_title': 'Diet Summary',
  'yoga_summary_title': 'Yoga Summary',
  'doctor_consult_summary_title': 'Doctor Consultation Summary',
  'summary_purpose': 'Purpose',
  'summary_precaution': 'Precaution',
  'summary_notice': 'Notice',
  'summary_eat': 'Khaayein',
  'summary_avoid': 'Avoid Karein',
  'summary_hydration': 'Paani / Hydration',
  'summary_poses': 'Poses',
  'summary_duration': 'Duration',
  'summary_safety': 'Safety',
  'summary_specialist': 'Specialist',
  'summary_when_to_visit': 'Kab Jayein',
  'summary_helpline': 'Helpline',
  'problem_summary_title': 'Problem Summary',
  'possible_reason_label': 'Possible Reason',
  'consult_doctor_card_title': 'Doctor Se Salah Lein',
  'view_advice_btn': 'Advice Dekhein',
  'see_more_btn': 'Aur Dekhein',
  'see_less_btn': 'Kam Dekhein',
  'see_more_helpline': 'Aur Dekhein (Advice & Helpline)',
  'doctor_helpline_title': 'Doctor Helpline (24x7)',
  'call_btn': 'Call Karein',
  'recommended_specialist': 'Recommended Specialist',
  'doctor_share_info': 'Doctor ko batane yogya zaroori baatein:',
  'reported_health_concern': 'Reported health problem',
  'symptom_duration': 'Kitne din se hai',
  'bring_medicines_note': 'Ongoing medicines aur allergy history sath le jayein',
  'category_recommended': 'Recommended',
  'category_avoid': 'Avoid Karein',
  'reported_problem': 'Aapki Problem',
  'risk_level': 'Guidance Level',
  'risk_low': 'Normal / General Care',
  'risk_moderate': 'Moderate — Sambhalke Care Karein',
  'risk_consult': 'Doctor se salah lena recommended hai',
  'risk_emergency': 'EMERGENCY: Turant Doctor ke paas jayein',
  'possible_causes_title': 'Sambhavit Kaaran (Possible Reasons)',
  'possible_causes_disclaimer': 'Note: Ye general information hai, confirmed medical diagnosis nahi. Sahi jaanch ke liye doctor se milein.',
  'general_tips': 'General Health Tips',

  // Food Section
  'food_title': 'Diet & Nutrition Suggestions',
  'food_recommended': 'Kya Khana Chahiye (Recommended)',
  'food_to_avoid': 'Kya Nahi Khana Chahiye (Avoid)',
  'hydration_guidance': 'Paani & Fluids Ki Advice',
  'food_safety_note': 'Ye food guidance aapki batayi gayi problem aur allergies ke according hai.',

  // Yoga Section
  'yoga_title': 'Yoga & Simple Exercises',
  'yoga_safety_warning': 'Agar koi serious pain ya bimari hai toh exercise shuru karne se pehle doctor se consult karein.',
  'duration_label': 'Duration',
  'instructions_label': 'Kaise Karein (Steps)',
  'precautions_label': 'Savdhaniyan',

  // Medicine Safety
  'medicine_safety_title': 'Medicine Safety & Guidance',
  'medicine_mandatory_warning': 'Important: Koi bhi medicine lene, band karne ya dose change karne se pehle doctor ya qualified healthcare professional se salah lein. CarePlus dawa nahi likhta.',
  'medicine_purpose': 'Kis Kaam Aati Hai (Purpose)',
  'medicine_precautions': 'Zaroori Savdhaniyan',
  'medicine_side_effects': 'Common Side Effects',
  'medicine_who_should_ask': 'Kise pehle doctor se puchna chahiye?',
  'medicine_source': 'Verified Reference Source',
  'reviewed_by_prefix': 'Reviewed by',
  'source_reference_label': 'Source',
  'important_interactions_label': 'Important Interactions',

  // Doctor Consultation
  'doctor_title': 'Doctor Consultation',
  'doctor_recommended_msg': 'Complete diagnosis aur physical checkup ke liye doctor se consult karna recommended hai.',
  'btn_find_doctor': 'Doctor Khojein',
  'btn_book_consult': 'Online Consult Book Karein',
  'btn_call_helpline': 'Helpline Par Call Karein',
  'btn_save_report': 'Health Report Save Karein',

  // Emergency Alert
  'emergency_alert_title': 'Emergency Alert (Turant Madad)',
  'emergency_alert_msg': 'Ye symptoms serious ho sakte hain. Kripya bina deri kiye turant hospital ya emergency helpline se contact karein.',
  'emergency_call_btn': 'Emergency Call Karein (112 / 108)',
  'emergency_nearby_hospital': 'Paas Ka Hospital Khojein',

  // My Health Profile
  'profile_title': 'Mera Health Profile',
  'profile_bmi': 'Body Mass Index (BMI)',
  'bmi_underweight': 'Kam Wajan (Underweight <18.5)',
  'bmi_normal': 'Normal & Healthy (18.5 - 24.9)',
  'bmi_overweight': 'Zyada Wajan (Overweight 25 - 29.9)',
  'bmi_obese': 'Motapa (Obesity ≥30)',
  'edit_profile': 'Profile Edit Karein',
  'saved_conditions': 'Purani Bimariyan',
  'saved_allergies': 'Allergies',
  'saved_medicines': 'Active Medicines',
  'health_records_count': 'Total Health Checks',

  // AI Assistant
  'ai_assistant_title': 'CarePlus AI Assistant',
  'ai_welcome_msg': 'Namaste! Main CarePlus AI hoon. Mujhse diet, yoga, home remedies ya medicine safety par questions puch sakte hain.',
  'ai_quick_prompt_1': 'Acidity me kya khana chahiye?',
  'ai_quick_prompt_2': 'Kamar dard ke liye safe yoga',
  'ai_quick_prompt_3': 'Sir dard ke gharelu upay',
  'ai_quick_prompt_4': 'Paracetamol ki precautions',
  'ai_type_hint': 'Apna sawal yahan likhein...',
  'ai_disclaimer_tag': 'CarePlus AI sirf educational jankari deta hai, dawai ka parcha nahi.',

  // Admin & Settings
  'settings_title': 'Settings & Privacy',
  'theme_mode': 'Theme Mode (Light / Dark)',
  'theme_switch_dark': 'Dark Mode On Karein',
  'theme_switch_light': 'Light Mode On Karein',
  'language_mode': 'App Ki Language',
  'elderly_mode': 'Bade Akshar Mode (Elderly Mode)',
  'elderly_mode_desc': 'Aasani se padhne ke liye font size bada karta hai.',
  'admin_panel': 'Admin Dashboard',
  'privacy_policy': 'Privacy Policy & Data Security',
  'terms_of_service': 'Terms & Conditions',
  'clear_health_data': 'Health Data Delete Karein',
  'delete_account': 'Account Delete Karein',
  'logout': 'Log Out',
  'confirm_clear_data': 'Kya aap sach me apna saved health data delete karna chahte hain?',
  'cancel': 'Cancel',
  'confirm': 'Delete Karein',
  'data_cleared_success': 'Data successfully delete ho gaya.',
  'error_generic': 'Kuch gadbad hui. Kripya dobara try karein.',
};
