const Map<String, String> stringsEn = {
  // App General
  'app_name': 'CarePlus',
  'tagline': 'Your Simple Health Guidance Companion',
  'disclaimer_title': 'Medical Safety & Guidance Disclaimer',
  'disclaimer_text':
      'CarePlus provides general health information and educational guidance. It is not a replacement for a professional doctor, formal clinical diagnosis, or emergency medical services. Always consult a qualified healthcare provider before starting, stopping, or changing any medication or treatment plan. In an emergency, please contact local emergency medical services immediately.',
  'disclaimer_accept': 'I Understand & Accept',
  'disclaimer_decline': 'Decline',

  // Navigation
  'nav_home': 'Home',
  'nav_my_health': 'My Health',
  'nav_suggestions': 'Suggestions',
  'nav_profile': 'Profile',
  'nav_ai_assistant': 'CarePlus AI',

  // Home Screen
  'home_greeting': 'Hello, Welcome to CarePlus',
  'home_subtext': 'Enter your health concern to get personalized, safe health guidance.',
  'home_main_cta': 'Check My Health',
  'home_quick_options': 'Quick Health Tools',
  'quick_problem': 'Health Problem',
  'quick_food': 'Food & Diet',
  'quick_yoga': 'Yoga & Exercise',
  'quick_medicine': 'Medicine Safety',
  'quick_doctor': 'Doctor Consult',
  'quick_emergency': 'Emergency Help',
  'recent_checks': 'Recent Health Checks',
  'no_recent_checks': 'No recent checks. Tap "Check My Health" to start.',
  'view_all_history': 'View All History',
  'daily_tip_title': 'Daily Health Insight',
  'daily_tip_body': 'Staying hydrated with 8–10 glasses of clean water daily helps digestion, energy levels, and kidney function.',

  // Patient Info Form
  'patient_info_title': 'Patient Information',
  'patient_info_subtitle': 'Please provide basic details to personalize health guidance.',
  'full_name': 'Full Name',
  'full_name_hint': 'e.g. John Doe / Anita Sharma',
  'age': 'Age (Years)',
  'age_hint': 'e.g. 35',
  'gender': 'Gender',
  'gender_male': 'Male',
  'gender_female': 'Female',
  'gender_other': 'Other',
  'weight_kg': 'Weight (kg)',
  'height_cm': 'Height (cm)',
  'location': 'Location (City / State)',
  'location_hint': 'e.g. Mumbai, New Delhi',
  'pregnancy_question': 'Is patient currently pregnant?',
  'yes': 'Yes',
  'no': 'No',
  'btn_next': 'Next: Health Problem',
  'btn_get_suggestions': 'Get Guidance',

  // Problem & Symptom Input
  'problem_input_title': 'Health Problem & Symptoms',
  'problem_input_subtitle': 'Type what you are experiencing in simple words.',
  'problem_hint': 'e.g. Headache since morning, feeling acidity after meals...',
  'select_common_problems': 'Or select common problems:',
  'symptoms_title': 'Select Associated Symptoms',
  'symptoms_search_hint': 'Search or add symptoms (e.g. Fever, Nausea)',
  'duration_title': 'How long have you had this problem?',
  'duration_1day': 'Today / Less than 24 hours',
  'duration_few_days': '2 – 3 days',
  'duration_1week': '1 – 2 weeks',
  'duration_chronic': 'More than a month',
  'existing_conditions': 'Existing Medical Conditions (if any)',
  'existing_conditions_hint': 'e.g. Diabetes, High BP, Asthma, Thyroid (comma separated)',
  'current_medicines': 'Current Medicines (if any)',
  'current_medicines_hint': 'e.g. Metformin 500mg, Multivitamin',
  'allergies': 'Allergies (if any)',
  'allergies_hint': 'e.g. Penicillin, Peanuts, Dust, Sulfa drugs',
  'btn_analyze': 'Analyze & Generate Guidance',

  // Health Analysis
  'analysis_in_progress': 'Analyzing Health Input...',
  'analysis_subtext': 'Evaluating symptoms, risk level, diet safety, and exercise recommendations...',

  // Health Result / Guidance Screen
  'result_title': 'Your Health Guidance',
  'tab_overview': 'Overview',
  'tab_food': 'Food & Diet',
  'tab_yoga': 'Yoga & Exercise',
  'tab_medicine': 'Medicine Safety',
  'tab_doctor': 'Doctor Advice',
  'reported_problem': 'Reported Concern',
  'risk_level': 'Guidance Level',
  'risk_low': 'Mild / General Care',
  'risk_moderate': 'Moderate — Self Care with Caution',
  'risk_consult': 'Medical Consultation Recommended',
  'risk_emergency': 'EMERGENCY: Immediate Medical Care Needed',
  'possible_causes_title': 'Possible Associated Factors',
  'possible_causes_disclaimer': 'Note: These are general possibilities, not a confirmed diagnosis. A licensed physician must evaluate symptoms for an accurate diagnosis.',
  'general_tips': 'General Wellness Suggestions',

  // Food Section
  'food_title': 'Food & Diet Suggestions',
  'food_recommended': 'Recommended Foods & Fluids',
  'food_to_avoid': 'Foods to Limit or Avoid',
  'hydration_guidance': 'Hydration Advice',
  'food_safety_note': 'Dietary suggestions are tailored to your reported allergies and conditions. Always listen to your body.',

  // Yoga Section
  'yoga_title': 'Yoga & Gentle Exercise',
  'yoga_safety_warning': '⚠️ Always consult a doctor before starting any physical exercise if you have pain, heart conditions, pregnancy, or chronic illness.',
  'duration_label': 'Duration',
  'instructions_label': 'Instructions',
  'precautions_label': 'Precautions',

  // Medicine Safety
  'medicine_safety_title': 'Medicine Safety & Education',
  'medicine_mandatory_warning': '⚠️ IMPORTANT: Consult a doctor or qualified pharmacist before starting, stopping, or changing the dosage of any medicine. CarePlus does not prescribe medications.',
  'medicine_purpose': 'General Purpose',
  'medicine_precautions': 'Common Precautions',
  'medicine_side_effects': 'Common Side Effects',
  'medicine_who_should_ask': 'Who should consult a doctor first?',
  'medicine_source': 'Educational Reference',

  // Doctor Consultation
  'doctor_title': 'Doctor Consultation',
  'doctor_recommended_msg': 'Consulting a qualified physician is recommended for proper diagnosis and physical examination.',
  'btn_find_doctor': 'Find a Doctor',
  'btn_book_consult': 'Book Online Consultation',
  'btn_call_helpline': 'Call Health Helpline',
  'btn_save_report': 'Save / Export Health Report',

  // Emergency Alert
  'emergency_alert_title': '⚠️ High Priority / Emergency Alert',
  'emergency_alert_msg': 'Your symptoms may indicate a condition requiring urgent medical intervention. Please do not delay.',
  'emergency_call_btn': 'Call Emergency Services (112 / 108 / 911)',
  'emergency_nearby_hospital': 'Find Nearest Emergency Hospital',

  // My Health Profile
  'profile_title': 'My Health Profile',
  'profile_bmi': 'Body Mass Index (BMI)',
  'bmi_underweight': 'Underweight (<18.5)',
  'bmi_normal': 'Healthy Weight (18.5 - 24.9)',
  'bmi_overweight': 'Overweight (25 - 29.9)',
  'bmi_obese': 'Obesity (≥30)',
  'edit_profile': 'Edit Profile',
  'saved_conditions': 'Known Conditions',
  'saved_allergies': 'Known Allergies',
  'saved_medicines': 'Active Medications',
  'health_records_count': 'Total Health Checks Completed',

  // AI Assistant
  'ai_assistant_title': 'CarePlus AI Assistant',
  'ai_welcome_msg': 'Namaste! I am CarePlus AI. Ask me any general health, diet, yoga, or medicine safety questions. How can I help you today?',
  'ai_quick_prompt_1': 'What should I eat when I have acidity?',
  'ai_quick_prompt_2': 'Safe exercises for lower back pain',
  'ai_quick_prompt_3': 'Home remedies for mild headache',
  'ai_quick_prompt_4': 'General precautions for Paracetamol',
  'ai_type_hint': 'Ask your health question in English or Hinglish...',
  'ai_disclaimer_tag': 'CarePlus AI provides educational information only, not medical prescriptions.',

  // Admin & Settings
  'settings_title': 'Settings & Preferences',
  'theme_mode': 'Theme Mode (Light / Dark)',
  'theme_switch_dark': 'Switch to dark mode',
  'theme_switch_light': 'Switch to light mode',
  'language_mode': 'App Language',
  'elderly_mode': 'Elderly / Large Text Mode',
  'elderly_mode_desc': 'Increases font size and contrast for comfortable reading.',
  'admin_panel': 'Admin & Content Management',
  'privacy_policy': 'Privacy Policy & Data Security',
  'terms_of_service': 'Terms of Service',
  'clear_health_data': 'Clear All Health Data',
  'delete_account': 'Delete Account',
  'logout': 'Log Out',
  'confirm_clear_data': 'Are you sure you want to delete all saved health records and profile information?',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'data_cleared_success': 'All health data cleared successfully.',
  'error_generic': 'Something went wrong. Please try again.',
};
