const Map<String, String> stringsHinglish = {
  // App General
  'app_name': 'CarePlus',
  'tagline': 'Sehat ki simple aur safe guidance.',
  'disclaimer_title': 'Medical Safety & Guidance Disclaimer',
  'disclaimer_text':
      'CarePlus general health information aur guidance provide karta hai. Ye doctor, diagnosis ya emergency medical service ka replacement nahi hai. Kisi bhi medicine ko start, stop ya change karne se pehle qualified healthcare professional se salah lein. Emergency situation me turant local emergency medical services se contact karein.',
  'disclaimer_accept': 'Main samajh gaya / Accept',
  'disclaimer_decline': 'Decline',

  // Navigation
  'nav_home': 'Home',
  'nav_my_health': 'My Health',
  'nav_suggestions': 'Suggestions',
  'nav_profile': 'Profile',
  'nav_ai_assistant': 'CarePlus AI',

  // Home Screen & Tabs
  'tab_diabetes': 'Diabetes',
  'tab_other': 'Other',
  'home_greeting': 'Hello, Welcome to CarePlus',
  'home_subtext': 'Apni health problem enter karein aur personalized general guidance paayein.',
  'home_main_cta': 'Check My Health',
  'diabetes_greeting': 'Diabetes aur Sugar Care',
  'diabetes_subtext': 'High/Low sugar, diet, walking aur blood sugar control ki safe guidance.',
  'diabetes_main_cta': 'Diabetes Checkup Shuru Karein',
  'home_quick_options': 'Quick Health Tools',
  'diabetes_quick_problems': 'Diabetes & Sugar Concerns',
  'quick_problem': 'Health Problem',
  'quick_food': 'Food & Diet',
  'quick_yoga': 'Yoga & Exercise',
  'quick_medicine': 'Medicine Safety',
  'quick_doctor': 'Doctor Consultation',
  'quick_emergency': 'Emergency Help',
  'recent_checks': 'Recent Health Checks',
  'no_recent_checks': 'Koi previous check nahi hai. "Start Health Checkup" dabayein.',
  'view_all_history': 'Pura History Dekhein',
  'daily_tip_title': 'Sehat Ki Baat (Daily Tip)',
  'daily_tip_body': 'Rozana 8-10 glass paani peene se digestion acha rehta hai aur body active rehti hai.',
  'diabetes_daily_tip_title': 'Daily Sugar Control Tip',
  'diabetes_daily_tip_body': 'Khana khane ke baad 15 minute ki walk karne se blood sugar spike nahi hota aur insulin behtar kaam karta hai.',
  'diabetes_home_remedies_title': 'Sugar Control Ke Liye Gharelu Tips',
  'diabetes_specialists_title': 'Top Verified Diabetologists',
  'other_specialists_title': 'Top Verified Specialists',
  'book_appointment': 'Book Consult',
  'call_clinic': 'Call Clinic',

  // Patient Info Form
  'patient_info_title': 'Patient Ki Basic Jankari',
  'patient_info_subtitle': 'Sahi suggestions ke liye kripya basic details fill karein.',
  'full_name': 'Pura Naam',
  'full_name_hint': 'jaise Anita Sharma / Rajesh Kumar',
  'age': 'Umar (Age in years)',
  'age_hint': 'jaise 35',
  'gender': 'Gender (Ling)',
  'gender_male': 'Purush (Male)',
  'gender_female': 'Mahila (Female)',
  'gender_other': 'Other',
  'weight_kg': 'Wajan (Weight in kg)',
  'height_cm': 'Height (cm me)',
  'location': 'City / Location (Optional)',
  'location_hint': 'jaise Mumbai, Delhi, Lucknow',
  'pregnancy_question': 'Kya patient pregnant hain?',
  'yes': 'Haan (Yes)',
  'no': 'Nahi (No)',
  'btn_next': 'Aage Badhein: Problem Details',
  'btn_get_suggestions': 'Suggestions Paayein',

  // Problem & Symptom Input
  'problem_input_title': 'Apni Health Problem Batayein',
  'problem_input_subtitle': 'Aapko kya takleef hai, simple shabdon me likhein.',
  'problem_hint': 'jaise: Pet me dard hai, sir bhari rehta hai, acidity hai...',
  'select_common_problems': 'Ya niche se common problem chunein:',
  'symptoms_title': 'Symptoms (Lakshan) Select Karein',
  'symptoms_search_hint': 'Lakshan search karein (jaise Fever, Vomiting, Pain)',
  'duration_title': 'Problem kab se hai?',
  'duration_1day': 'Aaj se / 24 ghante se kam',
  'duration_few_days': '2 – 3 din se',
  'duration_1week': '1 – 2 hafte se',
  'duration_chronic': 'Ek mahine se zyada',
  'existing_conditions': 'Pehle se koi bimari hai? (Optional)',
  'existing_conditions_hint': 'jaise Diabetes, High BP, Thyroid, Asthma',
  'current_medicines': 'Abhi kaunsi medicine chal rahi hai?',
  'current_medicines_hint': 'jaise Metformin, BP tablet, Gas capsule',
  'allergies': 'Kisi cheez se allergy hai? (Optional)',
  'allergies_hint': 'jaise Dust, Penicillin, Peanuts',
  'btn_analyze': 'Analyze Karein & Guidance Paayein',

  // Health Analysis
  'analysis_in_progress': 'Health Analysis Chal Raha Hai...',
  'analysis_subtext': 'Symptoms, risk level, food aur exercise suggestions ready kiye ja rahe hain...',

  // Health Result / Guidance Screen
  'result_title': 'Aapki Health Guidance',
  'tab_overview': 'Overview',
  'tab_food': 'Food & Diet',
  'tab_yoga': 'Yoga & Exercise',
  'tab_medicine': 'Medicine Safety',
  'tab_doctor': 'Doctor Advice',
  'reported_problem': 'Aapki Problem',
  'risk_level': 'Guidance Level',
  'risk_low': 'Normal / General Care',
  'risk_moderate': 'Moderate — Sambhalke Care Karein',
  'risk_consult': 'Doctor se salah lena recommended hai',
  'risk_emergency': 'EMERGENCY: Turant Doctor ke paas jayein',
  'possible_causes_title': 'Sambhavit Kaaran (Possible Factors)',
  'possible_causes_disclaimer': 'Dhyan de: Ye sirf general information hai, confirmed medical diagnosis nahi hai. Doctor se sahi janch karwayein.',
  'general_tips': 'General Health Tips',

  // Food Section
  'food_title': 'Food & Diet Suggestions',
  'food_recommended': 'Kya Khana Chahiye (Recommended)',
  'food_to_avoid': 'Kin Cheezon se Parhez Karein (Avoid)',
  'hydration_guidance': 'Paani & Liquid Guidance',
  'food_safety_note': 'Ye diet suggestions aapki batayi gayi allergies ke mutabiq hain.',

  // Yoga Section
  'yoga_title': 'Yoga & Exercise Suggestions',
  'yoga_safety_warning': 'Exercise start karne se pehle doctor ya qualified professional se salah lein agar dard ya chronic bimari ho.',
  'duration_label': 'Samay (Duration)',
  'instructions_label': 'Kaise Karein (Instructions)',
  'precautions_label': 'Savdhani (Precautions)',

  // Medicine Safety
  'medicine_safety_title': 'Medicine Safety Jankari',
  'medicine_mandatory_warning': 'Important: Koi bhi medicine lene, band karne ya dose change karne se pehle doctor ya qualified healthcare professional se salah lein.',
  'medicine_purpose': 'General Kaam (Purpose)',
  'medicine_precautions': 'Zaroori Savdhaniyan',
  'medicine_side_effects': 'Common Side Effects',
  'medicine_who_should_ask': 'Kise pehle doctor se puchna chahiye?',
  'medicine_source': 'Verified Source',

  // Doctor Consultation
  'doctor_title': 'Doctor Consultation',
  'doctor_recommended_msg': 'Doctor se salah lena recommended hai taaki physical checkup aur sahi evaluation ho sake.',
  'btn_find_doctor': 'Doctor Dhoondhein',
  'btn_book_consult': 'Consultation Book Karein',
  'btn_call_helpline': 'Helpline Par Call Karein',
  'btn_save_report': 'Health Report Save Karein',

  // Emergency Alert
  'emergency_alert_title': 'Emergency Warning',
  'emergency_alert_msg': 'Yeh lakshan gambhir ho sakte hain. Please turant hospital ya doctor se contact karein.',
  'emergency_call_btn': 'Emergency Call Karein (112 / 108)',
  'emergency_nearby_hospital': 'Nazdeeki Hospital Dhoondhein',

  // My Health Profile
  'profile_title': 'My Health Profile',
  'profile_bmi': 'BMI (Body Mass Index)',
  'bmi_underweight': 'Kam Wajan (Underweight <18.5)',
  'bmi_normal': 'Normal & Fit (18.5 - 24.9)',
  'bmi_overweight': 'Thoda Zyada Wajan (25 - 29.9)',
  'bmi_obese': 'Obese (≥30)',
  'edit_profile': 'Profile Edit Karein',
  'saved_conditions': 'Existing Bimariyan',
  'saved_allergies': 'Allergies',
  'saved_medicines': 'Active Medicines',
  'health_records_count': 'Total Health Checks',

  // AI Assistant
  'ai_assistant_title': 'CarePlus AI Assistant',
  'ai_welcome_msg': 'Namaste! Main CarePlus AI hoon. Mujhse food, yoga, lifestyle ya medicine safety ke baare me poochhein.',
  'ai_quick_prompt_1': 'Mujhe acidity hai, kya khana chahiye?',
  'ai_quick_prompt_2': 'Mere sir me dard hai, kya karun?',
  'ai_quick_prompt_3': 'Kaunsi exercise safe ho sakti hai?',
  'ai_quick_prompt_4': 'Is medicine ke common side effects kya hain?',
  'ai_type_hint': 'Apna sawal Hindi ya Hinglish me poochein...',
  'ai_disclaimer_tag': 'CarePlus AI sirf educational information deta hai, prescription nahi.',

  // Admin & Settings
  'settings_title': 'Settings & Privacy',
  'theme_mode': 'Theme Mode (Light / Dark)',
  'theme_switch_dark': 'Dark mode on karein',
  'theme_switch_light': 'Light mode on karein',
  'language_mode': 'App Bhasha (Language)',
  'elderly_mode': 'Bade Akshar Mode (Elderly Friendly)',
  'elderly_mode_desc': 'Aasaani se padhne ke liye font size bada karta hai.',
  'admin_panel': 'Admin Dashboard (Content CMS)',
  'privacy_policy': 'Privacy Policy & Data Suraksha',
  'terms_of_service': 'Terms & Conditions',
  'clear_health_data': 'Pura Health Data Delete Karein',
  'delete_account': 'Account Delete Karein',
  'logout': 'Logout Karein',
  'confirm_clear_data': 'Kya aap sach me apna saved health data delete karna chahte hain?',
  'cancel': 'Cancel',
  'confirm': 'Haan, Delete Karein',
  'data_cleared_success': 'Data safaltapurvak delete ho gaya.',
  'error_generic': 'Kuch problem aa gayi hai. Please dobara try karein.',
};
